config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :customers, only:[:index, :show, :edit, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    root to: 'homes#top'
    resources :items, only:[:index, :new, :create, :show, :edit, :update]
    resources :order_details, only:[:update]
    resources :orders, only:[:update]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :nullify
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre

  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  attachment :image

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer

  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { payment_waiting: 0, payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order

  enum making_status: { production_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3 }
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer)
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_passward, :postal_code, :address, :telephone_number, :is_active, :created_at, :updated_at)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name, :created_at, :update_at)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    def top
        @orders = Order.all
        @order_details = OrderDetail.all
    end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def index
    @items = Item.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_items_path
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :introduction, :price, :is_active, :created_at, :update_at)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
  end

  def update
  end

end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_admin!

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
  
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="col-md-2 offset-md-1">
  <h5 class="page_title"><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h5>
</div>
<div class="col-md-4 offset-md-1">
  <table class="table table-borderless">
  <tr>
    <th>会員ID</th>
    <td><%= @customer.id %></td>
  </tr>
  <%= form_with model: [:admin, @customer], local:true do |f| %>
  <tr>
    <th><label for="custome_last_name">氏名</label></th>
    <td>
      <%= f.text_field :last_name, class:"form-control last_name", id:"customer_last_name" %>
      <%= f.text_field :first_name, class:"form-control first_name", id:"customer_first_name" %>
    </td>
  </tr>
  <tr>
    <th><label for="custome_last_name_kana">フリガナ</label></th>
    <td>
      <%= f.text_field :last_name_kana, class:"form-control last_name_kana", id:"customer_last_name_kana" %>
      <%= f.text_field :first_name_kana, class:"form-control first_name_kana", id:"customer_first_name_kana" %>
    </td>
  </tr>
  <tr>
    <th><label for="customer_postal_code">郵便番号</label></th>
    <td>
      <%= f.text_field :postal_code,class:"form-control postal_code", id:"customer_postal_code" %>
    </td>
  </tr>
  <tr>
    <th><label for="customer_address">住所</label></th>
    <td>
      <%= f.text_field :address,class:"form-control address", id:"customer_address" %>
    </td>
  </tr>
  <tr>
    <th><label for="customer_telephone_number">電話番号</label></th>
    <td>
      <%= f.text_field :telephone_number,class:"form-control telephone_number", id:"customer_telephone_number" %>
    </td>
  </tr>
  <tr>
    <th><label for="customer_email">メールアドレス</label></th>
    <td>
      <%= f.text_field :email,class:"form-control email", id:"customer_email" %>
    </td>
  </tr>
  <tr>
    <th>会員ステータス</th>
    <td>
      <%= f.radio_button :is_active, true, checked: true %>有効
      <%= f.radio_button :is_active, false %>退会
    </td>
  </tr>
  </table>
    <div class="form-group">
      <%= f.submit '変更を保存', class:"btn btn-secondary" %>
    </div>
  <% end %>
  </div>

app/views/admin/customers/index.html.erb
<div class="col-md-2 offset-md-1">
  <h5 class="page_title">会員一覧</h5>
</div>
<div class="col-md-10 offset-md-1">
  <table class="table">
    <thead>
      <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <th><%= customer.id %></th>
          <th><%= link_to customer.last_name+customer.first_name, admin_customer_path(customer.id) %></th>
          <th><%= customer.email %></th>
          <th>
          <% if customer.is_active == true %>
          有効
          <% else %>
          退会
          <% end %>
        </th>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/customers/show.html.erb
<div class="col-md-3 offset-md-1">
  <h5 class="page_title"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h5>
</div>

<div class="col-md-4 offset-md-1">
<table class="table table-borderless">
  <tr>
    <th>会員ID</th>
    <td><%= @customer.id %></td>
  </tr>
  <tr>
    <th>氏名</th>
    <td><%= @customer.last_name %> <%= @customer.first_name %></td>
  </tr>
  <tr>
    <th>フリガナ</th>
    <td><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
  </tr>
  <tr>
    <th>郵便番号</th>
    <td><%= @customer.postal_code %></td>
  </tr>
  <tr>
    <th>住所</th>
    <td><%= @customer.address %></td>
  </tr>
  <tr>
    <th>電話番号</th>
    <td><%= @customer.telephone_number %></td>
  </tr>
  <tr>
    <th>メールアドレス</th>
    <td><%= @customer.email %></td>
  </tr>
  <tr>
    <th>会員ステータス</th>
    <td><%= @customer.is_active %></td>
  </tr>
</table>

<%= link_to "編集する", edit_admin_customer_path(@customer) %>
<%= link_to "注文履歴一覧を見る", admin_customers_path %>
</div>

app/views/admin/genres/edit.html.erb
<div class="offset-md-1">
  <h5 class="page_title">ジャンル一覧・追加</h5>
</div>
<div class="col-md-6 offset-1">
  <div class="form-inline">
  <%= form_with model: [:admin, @genre], local:true do |f| %>
    <div class="form-group">
      <label for="genre_name">ジャンル名</label>
      <%= f.text_field :name,class:"form-control genre_name", id:"genre_name" %>
    </div>
    <div class="form-group">
      <%= f.submit '変更を保存', class:"btn btn-success" %>
    </div>
  <% end %>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="offset-md-1">
  <h5 class="page_title">ジャンル一覧・追加</h5>
</div>

<div class="row">
  <div class="col-md-5 offset-md-1">
  <%= form_with model: [:admin, @genre], local:true do |f| %>
  <div class="form-inline">
    <div class="form-group">
      <label for="genre_name">ジャンル名</label>
      <%= f.text_field :name,class:"form-control genre_name", id:"genre_name" %>
    </div>
    <div class="form-group">
      <%= f.submit '新規登録', class:"btn btn-success" %>
    </div>
  </div>
  <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-4 offset-1">
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th>ジャンル</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @genres.each do |genre| %>
        <tr>
          <td>
            <%= genre.name %>
          </td>
          <td>
            <%= link_to '編集する', edit_admin_genre_path(genre.id), class: "btn btn-sm btn-success" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class="col-md-2 offset-md-1">
  <h5 class="page_title">商品編集</h5>
</div>
<div class="col-md-6 offset-md-1">
  <table class="table table-borderless">
  <%= form_with model: [:admin, @item], local:true do |f| %>
    <tr>
      <td><label for="item_image">商品画像</label></td>
      <td><%= f.attachment_field :image, class:"form-control-file item_image", id:"item_image" %></td>
    </tr>
    <tr>
      <td><label for="item_name">商品名</label></td>
      <td><%= f.text_field :name,class:"form-control name", id:"item_name" %></td>
    </tr>
    <tr>
      <td><label for="item_introduction">商品説明</label></td>
      <td><%= f.text_area :introduction, class:"form-control introduction", id:"item_introduction" %></td>
    </tr>
    <tr>
      <td>ジャンル</td>
      <td><%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "--選択してください--" %></td>
    </tr>
    <tr>
      <td><label for="item_price">税抜価格</label></td>
      <td><%= f.number_field :price, class:"form-control price", id:"item_price" %>円</td>
    </tr>
    <tr>
      <td>販売ステータス</td>
      <td>
        <%= f.radio_button :is_active, :true %>販売中
        <%= f.radio_button :is_active, :false %>販売停止中
      </td>
    </td>
  </table>
    <div class="form-group">
      <%= f.submit '変更を保存', class:"btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/admin/items/index.html.erb
<div class=row>
  <div class="col-md-2 offset-md-1">
    <h5 class="page_title">商品一覧</h5>
  </div>
  <%= link_to "＋", new_admin_item_path, class: 'btn btn-outline-secondary rounded-circle p-0' %>
</div>
<div class="col-md-10 offset-md-1">
<table class="table">
  <thead>
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <th><%= item.id %></th>
        <th><%= link_to item.name, admin_item_path(item.id) %></th>
        <th><%= item.price %></th>
        <th><%= item.genre.name %></th>
        <th>
          <% if item.is_active == true %>
          販売中
          <% else %>
          販売停止中
          <% end %>
        </th>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/admin/items/new.html.erb
<div class="col-md-2 offset-md-1">
  <h5 class="page_title">商品新規登録</h5>
</div>
<div class="col-md-5 offset-md-4">
  <table class="table table-borderless">
  <%= form_with model: [:admin, @item], local:true do |f| %>
    <tr>
      <td><label for="item_image">商品画像</label></td>
      <td><%= f.attachment_field :image, class:"form-control-file item_image", id:"item_image" %></td>
    </tr>
    <tr>
      <td><label for="item_name">商品名</label></td>
      <td><%= f.text_field :name,class:"form-control name", id:"item_name" %></td>
    </tr>
    <tr>
      <td><label for="item_introduction">商品説明</label></td>
      <td><%= f.text_area :introduction, class:"form-control introduction", id:"item_introduction" %></td>
    </tr>
    <tr>
      <td>ジャンル</td>
      <td><%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "--選択してください--" %></td>
    </tr>
    <tr>
      <td><label for="item_price">税抜価格</label></td>
      <td><%= f.number_field :price, class:"form-control price", id:"item_price" %>円</td>
    </tr>
    <tr>
      <td>販売ステータス</td>
      <td>
        <%= f.radio_button :is_active, true %>販売中
        <%= f.radio_button :is_active, false %>販売停止中
      </td>
    </tr>
  </table>
    <div class="form-group">
      <%= f.submit '新規登録', class:"btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/admin/items/show.html.erb
<div class="col-md-2 offset-md-1">
  <h5 class="page_title">商品詳細</h5>
</div>
<div class="row">
  <div class="col-md-4 offset-md-1">
    <%= attachment_image_tag @item, :image, format: 'jpeg', size: "300x200" %>
  </div>
  <div class="col-md-5">
    <table class="table table-borderless">
      <tr>
        <td>商品名</td>
        <td><%= @item.name %></td>
      </tr>
      <tr>
        <td>商品説明</td>
        <td><%= @item.introduction %></td>
      </tr>
      <tr>
        <td>ジャンル</td>
        <td><%= @item.genre.name %></td>
      </tr>
      <tr>
        <td>税込価格<br>(税抜価格)</td>
        <td><%= @item.price + @item.price*0.1 %>(<%= @item.price %>)円</td>
      </tr>
      <tr>
        <td>販売ステータス</td>
        <td>
          <% if @item.is_active == true %>
          販売中
          <% else %>
          販売停止中
          <% end %>
        </td>
      </tr>
    </table>
    <%= link_to "編集する", edit_admin_item_path(@item), class:"btn btn-success" %>
  </div>
</div>